// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhiefjxijiwwcvlppcbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoaWVmanhpaml3d2N2bHBwY2JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MTE2NzksImV4cCI6MjA2NzI4NzY3OX0.9Ed2znlhxiiZJ9eexzejGR0NZJiXDffSh59U3tiEEhU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});